col username for a30
col instance_name for a20
col startup_time for a25
col owner for a20
col table_name for a30
col index_name for a30
col object_name for a30
col object_owner for a20
col host_name for a30
col profile for a12
col machine for a30
col shemaname for a12
col column_name for a20
col degree for a6
col partitioned for a12
col visibility for a10
col partition_name for a30
col key_column_name for a20
col high_value for a12
col sequence_name for a20
col cycle_flag for a10
col order_flag for a10
col log_owner for a16
col master for a12
col log_table for a30
col object_id for 9999999999
col mview_name for a20
col last_refresh_type for a20
col base_table_owner for a20
col base_table_name for a20
col type for a12
col object_type for a18
col account_status for a20
col default_tablespace for a20
col master_link for a16
col PLAN_TABLE_OUTPUT for a120
col stock_name for a40
col marcket_name for a20
col industry_name for a20
col stock_unit for a16
col nikkei225 for a10
col career for a48
col draft for a16
col flg for a4
col str for a20
